Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.network "forwarded_port", guest: 8124, host: 8124
  config.vm.provision :shell,
    :inline => "sudo apt-get update && sudo apt-get -y install build-essential git ruby1.9.3 && sudo gem install github-pages therubyracer --no-ri --no-rdoc"
  config.vm.provision :shell,
     :inline => "cd /home/jekyll && su vagrant - -c \"jekyll server --watch -P 8124 --force_polling\"",
     run: "always"

  config.vm.synced_folder "./",
    "/home/jekyll",
    :owner => "vagrant",
    :group => "vagrant",
    type: "rsync",
    rsync__auto: "true",
    rsync__exclude: [".git/", ".idea/", "_site/"],
    rsync__args: ["--verbose", "-r", "-l", "--delete", "--stats"]

end